window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0372_Smart Choice Update_Switch NSW-SA_300x250",
  "Creative": "AGA0372_Smart Choice Update_Switch NSW-SA",
  "Creative_Dimension": "300x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.025,F2:2.5,F3:1,F4:2,F5:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*You must stay with AGL at the same address\nfor 90 days from the commencement of the electricity/gas plan to receive this credit. Sign up online for one-off bill credits on selected AGL Electricity and Gas plans for new and moving residential customers only in NSW and SA\nwhere AGL operates. Credits are GST inclusive, non-transferable, non-refundable. Full T&Cs at agl.com.au",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"[[The smart choice]]\",\"size\":\"28\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Subheadline": "{\"text\":\"Switch and stay\",\"size\":\"26\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": ",",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F2_Image1_8a46521b.svg\",\"size\":\"0\",\"position\":\"15 80\",\"svgType\":\"\",\"animationIn\":\"moveInRight:1::power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F2_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"16\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F3_Image1_8a46521b.svg\",\"size\":\"\",\"position\":\"15 80\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.75::1\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "colorWheel:1.7",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F4_Image1_8a46521b.svg\",\"size\":\"\",\"position\":\"15 80\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.75::1\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F2_Image1_8a46521b.svg\",\"size\":\"\",\"position\":\"15 80\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F5_Image2_8a46521b.svg\",\"size\":\"\",\"position\":\"225 10\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"[[The smart choice]]\",\"size\":\"28\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F5_Subheadline": "{\"text\":\"Switch and stay\",\"size\":\"26\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F5_Cta": "{\"text\":\"SWITCH NOW\",\"alignment\":\"flex-start\",\"style\":\"\",\"position\":null,\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};