window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0372_Smart Choice Update_Switch VIC_640x200",
  "Creative": "AGA0372_Smart Choice Update_Switch VIC",
  "Creative_Dimension": "640x200",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:1,F3:1,F4:2,F5:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*Online sign-up bill credits on selected AGL Electricity and Gas plans for new and moving customers only in VIC where AGL operates. ​Credits are GST inclusive, one-off, non-transferable, non-refundable and will appear on your first bill. Full T&Cs at agl.com.au",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",middle",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"640 200\",\"position\":\"8 5\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":true}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"[[The smart choice]]\\nSwitch to AGL\",\"size\":\"40\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": ",",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_VIC_F2_Image1_15156f12.svg\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.5:20:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F2_Headline": "{\"text\":\"\",\"size\":\"30\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_VIC_F3_Image1_15156f12.svg\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.5:20:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "colorWheel:1.7",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_VIC_F4_Image1_15156f12.svg\",\"size\":\"\",\"position\":\"480 65\",\"svgType\":\"\",\"animationIn\":\"scaleUp:0.5:1.1:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_VIC_F5_Image1_15156f12.svg\",\"size\":\"\",\"position\":\"0 5\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"[[The smart choice.]] Switch to AGL.\",\"size\":\"26\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F5_Cta": "{\"text\":\"SWITCH NOW\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};