window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0302_Netflix Relaunch - Bridgerton_Display_640x200",
  "Creative": "AGA0302_Netflix Relaunch - Bridgerton_Display",
  "Creative_Dimension": "640x200",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.1,F2:2,F3:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*AGL Netflix Plan includes Netflix Standard with ads with option to upgrade tiers at an extra cost. T&Cs apply. Basic Plan Information Documents (NSW, QLD, SA) are available at agl.com.au/bpid. Fact Sheets (VIC) are available at agl.com.au/vefs. For clear advice on the right plan for you, contact AGL on 131 245.",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,",
  "F1_LayoutClass": ",middle",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_InframeImage_3d066e5c.jpg\",\"size\":\"226 200\",\"position\":\"0 0 0 0\",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":\"moveInRight:1.5::power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_Logo_3d066e5c.svg\",\"alignment\":null,\"position\":\"0 -0.8 0 0\",\"padding\":\"0\",\"maxSize\":null}",
  "F1_Headline": "{\"text\":null,\"size\":\"32\",\"weight\":null,\"order\":\"2\",\"column\":null}",
  "F1_Subheadline": "{\"text\":\"\\n\",\"size\":\"10\",\"weight\":null,\"order\":null,\"column\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F1_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F1_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",top",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":\"0 0\",\"svgType\":null,\"animationIn\":\"moveInRight:2.5::power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_InframeImage_3d066e5c.jpg\",\"size\":\"226 200\",\"position\":\"0 0 0 0\",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_Logo_3d066e5c.svg\",\"alignment\":null,\"position\":\"0 -0.8 0 0\",\"padding\":\"0\",\"maxSize\":null}",
  "F2_Headline": "{\"text\":\"[Can’t live without Netflix?]\",\"size\":\"32\",\"weight\":null,\"order\":null,\"column\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":\"0\",\"weight\":null,\"order\":null,\"column\":null}",
  "F2_icontext": "{\"text\":null,\"size\":\"16\",\"weight\":null,\"order\":null,\"column\":null}",
  "F2_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F2_Terms": "{\"text\":\"\\n\",\"alignment\":null,\"style\":null,\"position\":\"packed\",\"column\":null}",
  "F2_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":\"packed\",\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F3_Transitions": "",
  "F3_Animations": "slideInByLine:0.5,",
  "F3_LayoutClass": ",top",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_InframeImage_3d066e5c.jpg\",\"size\":\"226 200\",\"position\":\"0 0 0 0\",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"assets/AGA0302_Netflix_Relaunch_-_Bridgerton_Display_F1_Logo_3d066e5c.svg\",\"alignment\":null,\"position\":\"0 -0.8 0 0\",\"padding\":null,\"maxSize\":null}",
  "F3_Headline": "{\"text\":\"[Join the AGL Netflix \\nElectricity Plan]\",\"size\":\"32\",\"weight\":600,\"order\":null,\"column\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F3_icontext": "{\"text\":\"and get |<span style='letter-spacing: -0.12em'>$</span>|120 RRP of Netflix value\\nincluded each year for the life of your plan*\",\"size\":\"16\",\"weight\":null,\"order\":null,\"column\":null}",
  "F3_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":\"packed\",\"column\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F4_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F4_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F4_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}"
};