window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0015_Choice/Control _Pension_300x250",
  "Creative": "HOP0015_Choice/Control _Pension",
  "Creative_Dimension": "300x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:1.5,F2:4.8,F3:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "General advice only. Consider the relevant PDS and TMD available at hostplus.com.au before making a decision. Issued by Host-Plus Pty Limited.",
  "CustomCSS": ".F1 .cta {opacity:0!important; }\n.cta-logo { align-items: flex-end!important;}\n.tapPacked { max-height: 43px!important;}\n\n",
  "Layouts": ",,,,",
  "F1_Transitions": "fadeIn:.3",
  "F1_Animations": "slideLineByLine:0.5,",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":\"fadeOut:0.2:power1.in\",\"frameOut\":null}",
  "F1_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F1_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F1_Headline": "{\"text\":\"CONTROL \\nOVER HOW\\n[your super::drop::\\niS Invested\",\"size\":\"30\",\"weight\":null,\"padding\":\"10 0 0 0\",\"order\":null,\"column\":null,\"delay\":\"0.5\",\"out\":null}",
  "F1_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F1_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideLineByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"assets/HOP0015_Choice_Control__Pension_F2_Video_2e782381.mp4\",\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":\"fadeOut:0.2:power1.in\",\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F2_Tap": "{\"url\":\"select option\",\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F2_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F2_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F2_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F2_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F3_Transitions": "",
  "F3_Animations": "slideLineByLine:0.5,",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F3_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_inline.svg\",\"position\":null,\"maxSize\":\"100\",\"alignment\":null,\"delay\":\".7\"}",
  "F3_Headline": "{\"text\":\"CONTROL \\nOVER HOW\\n[your super::drop::\\niS Invested\",\"size\":\"30\",\"weight\":null,\"padding\":\"10 0 0 0\",\"order\":null,\"column\":null,\"delay\":\"0.25\",\"out\":null}",
  "F3_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F3_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F3_Cta": "{\"text\":\"Learn more\",\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":\"2\",\"out\":null}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":null,\"ospSize\":null}",
  "F4_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F4_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F4_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F4_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":null,\"ospSize\":null}",
  "F5_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F5_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}"
};