window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0087_Fund For Life_NRL_970x250",
  "Creative": "HOP0087_Fund For Life_NRL",
  "Creative_Dimension": "970x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "",
  "CustomCSS": ".background1 {\noverflow: unset;\nz-index: 2;\n}\n\n.background2 {\noverflow: hidden;\nz-index: 2;\nwidth: 700px\n\n}\n\n.background2 img {\nposition: absolute;\ntransform: translateX(-240px);\nanimation: slideRight 1.24s ease 0.7s forwards;\n}\n\n@keyframes slideRight {\n  to {\n    transform: translateX(780px);\n  }\n}\n\n.logo img {\nheight: auto\n}",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideLineByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",middle",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_CustomHTML": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"350\",\"position\":\"970 -50\",\"animationIn\":\"moveInRight:1.2:1100:power1.out:0.7\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image2": "{\"url\":\"assets/HOP0087_Fund_For_Life_NRL_F1_Image2_22a0849c.svg\",\"size\":\"240\",\"position\":\"0 \",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"assets/HOP0087_Fund_For_Life_NRL_F1_Logo_22a0849c.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":false,\"ospSize\":\"7.35\"}",
  "F1_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F1_Headline": "{\"text\":\"Wherever you\\n[are in life]\",\"size\":\"70\",\"weight\":\"\",\"padding\":\"\",\"order\":\"1\",\"column\":\"\",\"delay\":\"0.9\",\"out\":\"\"}",
  "F1_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F1_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Terms": "{\"text\":\"Issued by Host-Plus Pty Limited. Consider the PDS and TMD available at hostplus.com.au before making a decision.\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideLineByLine:0.5,",
  "F2_LayoutClass": ",middle",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_CustomHTML": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"assets/HOP0087_Fund_For_Life_NRL_F1_Logo_22a0849c.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":false,\"ospSize\":\"7.35\"}",
  "F2_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"1.2\"}",
  "F2_Headline": "{\"text\":\"[TACKLE YOUR\\nRETIREMENT GOALS]\",\"size\":\"70\",\"weight\":\"\",\"padding\":\"\",\"order\":\"1\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"Hostplus can help you\",\"size\":\"35\",\"weight\":\"\",\"padding\":\"\",\"order\":\"0\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F2_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Terms": "{\"text\":\"Issued by Host-Plus Pty Limited. Consider the PDS and TMD available at hostplus.com.au before making a decision.\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F2_Cta": "{\"text\":\"Compare Hostplus\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"2\",\"out\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_CustomHTML": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F3_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F3_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_CustomHTML": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F4_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F4_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_CustomHTML": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F5_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F5_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}"
};