window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "YOU0070_Flexible Cover_Retargeting_970x250",
  "Creative": "YOU0070_Flexible Cover_Retargeting",
  "Creative_Dimension": "970x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "BorderColor": "",
  "BorderRadius": "35px 35px 35px 0px",
  "CustomCSS": ".termsFade { display: block; padding-bottom: 9px}\n\n@keyframes fadeTermsAnimate {\n  10% { opacity:1; }\n  90% { opacity:1; }\n  100% { opacity:0; }\n}\n\n.footer-left .terms {\nmargin: 0px 0px 4px 344px!important;\n}\n\n.cta {margin-top: 8px!important}\n\n.termsFade {\n  opacity: 0;\n}\n\n.F1 .termsFade {\n  animation-name: fadeTermsAnimate;\n  animation-duration: 3.8s;\n  animation-delay: 0s;\n  animation-fill-mode: forwards;\n}\n\n.termsPanelContent {\nfont-size: 12px!important}",
  "ExitLink": "",
  "Terms": "Conditions apply. Product issued by Youi Pty Ltd. Consider our Home Insurance PDS to decide if this product is right for you. PDS and TMD available at youi.com.au.",
  "TermsLabel": "<span class='termsFade'>Conditions apply.</span>{{More information >}}",
  "TermsLabelPosition": "0 0 9px 344px",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideUpByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/YOU0070_Flexible_Cover_Retargeting_F1_Image1_1ccf9de9.jpg\",\"size\":\"310 200\",\"position\":\"25 25\",\"border\":\"15 15 15 0\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F1_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"839 143\",\"padding\":\"\",\"maxSize\":\"104 80\"}",
  "F1_Headline": "{\"text\":\"Flexible home\\ninsurance.\",\"size\":\"44\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"10 0 0 344\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideUpByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F2_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"839 143\",\"padding\":\"\",\"maxSize\":\"104 80\"}",
  "F2_Headline": "{\"text\":\"Shop home insurance that’s \\na bit more you-shaped.\",\"size\":\"44\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"10 0 0 344\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Cta": "{\"text\":\"Shop now\",\"alignment\":\"\",\"style\":\"\",\"position\":\"packed\",\"padding\":\"0 0 0 344\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"large\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F3_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F4_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F5_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};