window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "YOU0070_SevereWeather_Retargeting_728x90",
  "Creative": "YOU0070_SevereWeather_Retargeting",
  "Creative_Dimension": "728x90",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:4.4,F2:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "BorderColor": "",
  "BorderRadius": "20px 20px 20px 0px",
  "CustomCSS": ".termsLink {padding-left: 210px; width: 300px}\n.termsFade {display: block;  width: 400px; padding-bottom: 6px}\n.leaderboard .inlineFrame {\n  padding: 9px 19px !important;\n  height: 70px !important;\n}\n@keyframes fadeTermsAnimate {\n  10% { opacity:1; }\n  90% { opacity:1; }\n  100% { opacity:0; }\n}\n\n.termsFade {\n  opacity: 0;\n}\n\n.F1 .termsFade {\n  animation-name: fadeTermsAnimate;\n  animation-duration: 6.2s;\n  animation-delay: 0s;\n  animation-fill-mode: forwards;\n}\n\n.hasInframeImage .terms { \nmargin-top: 0px!important;\nbottom: 0px!important;\n}",
  "ExitLink": "",
  "Terms": "Loss or damage caused by storm or flood within the first 72 hours of your policy commencing is only covered in limited circumstances. Exclusions and conditions apply. \nProduct issued by Youi Pty Ltd. Consider our Home & Contents PDS to decide if this product is right for you. PDS and TMD available at youi.com.au.",
  "TermsLabel": "<span class='termsFade'>Loss or damage caused by storm or flood within the first 72 hours of your policy<br>commencing is only covered in limited circumstances. Exclusions and conditions apply.</span>{{More information >}}",
  "TermsLabelPosition": "",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideUpByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",top",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/YOU0070_SevereWeather_Retargeting_F1_Image1_4771662a.jpg\",\"size\":\"210 70\",\"position\":\"9 9\",\"border\":\"10px 10px 10px 0px\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F1_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"Cover for storm and flood.\",\"size\":\"22\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"0 0 0 210px\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideUpByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F2_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F2_Headline": "{\"text\":\"Shop home insurance that’s\\na bit more you-shaped.\",\"size\":\"22\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"0 0 0 210px\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Cta": "{\"text\":\"Shop now\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"large\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F3_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F4_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F5_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};