window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0277_Q2 SME Mailer & Toolkit_Display_728x90",
  "Creative": "AGA0277_Q2 SME Mailer & Toolkit_Display",
  "Creative_Dimension": "728x90",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.5,F2:2,F3:2,F4:2,F5:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*AGL Small business energy plans areavailable in VIC, NSW, QLD and SA, in areas where AGL operates for small business customers. Plans have variable rates.Plan Terms & Conditions apply. Basic Plan Information Documents (NSW, SA & QLD) are available at agl.com.au/bpid. Fact Sheets (Vic) available at agl.com.au/vefs. For clear advice on the right plan for you, contact AGL on 131 245.",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": ",",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Image1_2d10a44a.svg\",\"size\":null,\"position\":\"0 0\",\"svgType\":null,\"animationIn\":\"moveInRight:1::power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Logo_2d10a44a.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F1_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F1_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",middle",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":\"0 0\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Logo_2d10a44a.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F2_Headline": "{\"text\":\"[[Energy to help]] your business grow\",\"size\":\"21\",\"weight\":600,\"order\":null,\"column\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F2_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F2_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F3_Transitions": "",
  "F3_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F3_LayoutClass": ",middle",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Logo_2d10a44a.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F3_Headline": "{\"text\":\"See if you could save with our low energy rates*\",\"size\":\"21\",\"weight\":400,\"order\":null,\"column\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F3_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F4_Transitions": "colorWheel:1.7",
  "F4_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F4_LayoutClass": ",middle",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Logo_2d10a44a.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F4_Headline": "{\"text\":\"Switch in minutes\",\"size\":\"21\",\"weight\":400,\"order\":null,\"column\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F4_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",middle",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Image1_2d10a44a.svg\",\"size\":null,\"position\":\"0 0\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":\"assets/AGA0277_Q2_SME_Mailer___Toolkit_Display_F1_Logo_2d10a44a.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F5_Headline": "{\"text\":\"[[Energy to help]] your business grow\",\"size\":\"21\",\"weight\":600,\"order\":null,\"column\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F5_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F5_Cta": "{\"text\":\"LEARN MORE\",\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":\"large\",\"fontSize\":null,\"column\":null}"
};