window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0064_Awards Medley_NRL_970x250",
  "Creative": "HOP0064_Awards Medley_NRL",
  "Creative_Dimension": "970x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:6,F2:1.5",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "Awards and ratings are only one factor to consider when choosing a super fund. Visit hostplus.com.au/awards to learn more about our awards. Issued by Host-Plus Pty Limited.    General advice only. Consider the relevant PDS and TMD available at hostplus.com.au before making a decision.",
  "CustomCSS": ".logo img {height: 98px!important}",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": ",",
  "F1_LayoutClass": ",top",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F1_Image1_d9055f3e.svg\",\"size\":\"970 250\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"fadeOutLeft:0.25:0:power1.in\",\"frameOut\":\"\",\"animatedSVG\":true}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F1_Logo_d9055f3e.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":false,\"ospSize\":\"\"}",
  "F1_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F1_Headline": "{\"text\":\"\",\"size\":\"80\",\"weight\":\"\",\"padding\":\"2 0 0 180\",\"order\":\"\",\"column\":\"\",\"delay\":\"0.5\",\"out\":\"\"}",
  "F1_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F1_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":\"right\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideLineByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F2_Image1_d9055f3e.svg\",\"size\":\"100 100\",\"position\":\"391 65\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:1.2\",\"animationOut\":\"fadeOutLeft:0.25:100:power1.in\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F2_Image2": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F2_Image2_d9055f3e.svg\",\"size\":\"100 100\",\"position\":\"502 65\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:1.7\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F2_Image3": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F2_Image3_d9055f3e.svg\",\"size\":\"100 100\",\"position\":\"609 65\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:2.2\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F1_Logo_d9055f3e.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":false,\"ospSize\":\"\"}",
  "F2_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_packed.svg\",\"position\":\"\",\"maxSize\":\"298\",\"alignment\":\"\",\"delay\":\"1.6\"}",
  "F2_Headline": "{\"text\":\"hostplus\\n[best super \\nfund winner]\",\"size\":\"47\",\"weight\":\"\",\"padding\":\"20 0 10 0\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F2_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":\"right\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F2_Cta": "{\"text\":\"Compare Hostplus\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"3.1\",\"out\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"fadeOutRight:0.5:100:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"162 178\",\"position\":\"20 48\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"fadeOutRight:0.25:100:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"assets/HOP0064_Awards_Medley_NRL_F1_Logo_d9055f3e.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F3_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"80\",\"weight\":\"\",\"padding\":\"2 0 0 180\",\"order\":\"\",\"column\":\"\",\"delay\":\"0.5\",\"out\":\"\"}",
  "F3_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F3_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Terms": "{\"text\":\"\",\"alignment\":\"right\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"fadeIn:0.5:power1.out:0\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F4_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_packed.svg\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"tap-left\",\"delay\":\"1.7\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F4_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Terms": "{\"text\":\"\",\"alignment\":\"right\",\"style\":\"\",\"position\":null,\"out\":\"\",\"padding\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"right\",\"position\":null,\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": "slideLineByLine:0.5,",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"110\",\"position\":\"366 44\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:1.2\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"112\",\"position\":\"494 44\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:1.7\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"110\",\"position\":\"626 48\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:2.2\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":false}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":false,\"ospSize\":\"\"}",
  "F5_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_packed.svg\",\"position\":\"\",\"maxSize\":\"298\",\"alignment\":\"\",\"delay\":\"1.7\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"47\",\"weight\":\"\",\"padding\":\"20 0 10 0\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F5_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"right\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"2.8\",\"out\":\"\"}"
};