window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "YOU0064_DR_Leisure_Lifestyle_Protect_728x90",
  "Creative": "YOU0064_DR_Leisure_Lifestyle_Protect",
  "Creative_Dimension": "728x90",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "BorderColor": "",
  "BorderRadius": "15px 15px 15px 0px",
  "CustomCSS": ".cta {padding: .55em 1em .65em!important}",
  "ExitLink": "",
  "Terms": "Product issued by Youi Pty Ltd. Consider our Small Business PDS when deciding if this product is right for you. PDS and TMD available at youi.com.au.",
  "TermsLabel": "{{More information >}}",
  "TermsLabelPosition": "",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideUpByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",middle",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":\"84 15\",\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_ProductIcon": "{\"url\":\"https://s0.2mdn.net/creatives/assets/4898779/YOUI0001_Icons_SmallBusiness.svg\",\"size\":\"39\",\"position\":\"18 0 0 20px\",\"padding\":\"368 0 0 98\",\"layout\":\"overlay\",\"delay\":null,\"animationIn\":null,\"animationOut\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"delay\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"border\":null}",
  "F1_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"inline\",\"position\":\"642 19\",\"padding\":null,\"maxSize\":\"65\"}",
  "F1_Headline": "{\"text\":\"Protect your tools of the trade.\",\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":\"0 0 16 51px\",\"delay\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F1_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":\"packed\",\"padding\":null,\"absolutePosition\":null,\"delay\":null,\"size\":\"large\",\"fontSize\":null,\"column\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideUpByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_ProductIcon": "{\"url\":\"https://s0.2mdn.net/creatives/assets/4898779/YOUI0001_Icons_SmallBusiness.svg\",\"size\":\"39\",\"position\":\"18 0 0 20px\",\"padding\":\"368 0 0 98\",\"layout\":\"overlay\",\"delay\":null,\"animationIn\":null,\"animationOut\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"delay\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"border\":null}",
  "F2_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"inline\",\"position\":\"642 19\",\"padding\":null,\"maxSize\":\"65\"}",
  "F2_Headline": "{\"text\":\"Shop Optional Business Items cover.\",\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":\"8 0 0 51px\",\"delay\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F2_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F2_Cta": "{\"text\":\"Shop now\",\"alignment\":null,\"style\":null,\"position\":\"footer\",\"padding\":\"0 86 0 0px\",\"absolutePosition\":null,\"delay\":null,\"size\":\"large\",\"fontSize\":null,\"column\":null}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"layout\":null,\"delay\":null,\"animationIn\":null,\"animationOut\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"delay\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"border\":null}",
  "F3_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F3_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F3_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"padding\":null,\"absolutePosition\":null,\"delay\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"layout\":null,\"delay\":null,\"animationIn\":null,\"animationOut\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"delay\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"border\":null}",
  "F4_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F4_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F4_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F4_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"padding\":null,\"absolutePosition\":null,\"delay\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"border\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"layout\":null,\"delay\":null,\"animationIn\":null,\"animationOut\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"padding\":null,\"delay\":null,\"order\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"border\":null}",
  "F5_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F5_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null,\"position\":null,\"padding\":null,\"delay\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"padding\":null,\"absolutePosition\":null,\"delay\":null,\"size\":null,\"fontSize\":null,\"column\":null}"
};