window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0318_SME Credit Offer_Display QLD SA_160x600",
  "Creative": "AGA0318_SME Credit Offer_Display QLD SA",
  "Creative_Dimension": "160x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.05,F2:2,F3:2,F4:2,F5:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*|$300| electricity credit and |$200| gas credit for new and moving Small Business customers ++who stay for at least 90 days++ on selected plans only. Credits include GST and are non-transferable & non-refundable. T&Cs apply.",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": ",",
  "F1_LayoutClass": ",top",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F1_Image1_8f9cea47.jpg\",\"size\":\"160\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F1_InframeImage_8f9cea47.svg\",\"size\":\"\",\"position\":\"153 0\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"moveInRight:0.5::power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"logo-wedge\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",middle",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"logo-wedge\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"0\"}",
  "F2_Headline": "{\"text\":\"\\nSwitch\\nand stay\\n[[with AGL]]\",\"size\":\"29\",\"weight\":600,\"order\":\"2\",\"column\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":null,\"column\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F3_LayoutClass": ",top",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F3_Image1_8f9cea47.svg\",\"size\":\"\",\"position\":\"12 200\",\"svgType\":\"\",\"animationIn\":\"moveInRight:1.5:500:power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F3_InframeImage_8f9cea47.png\",\"size\":\"\",\"position\":\"0 0\",\"order\":\"1\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"logo-wedge\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"0\"}",
  "F3_Headline": "{\"text\":\"For up to \",\"size\":\"17\",\"weight\":600,\"order\":\"\",\"column\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"2\",\"column\":\"\"}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "colorWheel:1.7:110 560",
  "F4_Animations": "slideInByLine:0.5,",
  "F4_LayoutClass": ",middle",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"logo-wedge\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"|That’s $300 for\\nelectricity and\\n$200 for gas|*\",\"size\":\"17\",\"weight\":400,\"order\":\"\",\"column\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",top",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F5_Image1_8f9cea47.svg\",\"size\":\"\",\"position\":\"12 190\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F1_Image1_8f9cea47.jpg\",\"size\":\"160\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F1_InframeImage_8f9cea47.svg\",\"size\":\"\",\"position\":\"0 154\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"assets/AGA0318_SME_Credit_Offer_Display_QLD_SA_F5_InframeImage_8f9cea47.png\",\"size\":\"160\",\"position\":\"0 0\",\"order\":\"1\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"logo-wedge\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"24\",\"weight\":600,\"order\":\"1\",\"column\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F5_Cta": "{\"text\":\"LEARN MORE\",\"alignment\":\"center\",\"style\":\"\",\"position\":null,\"absolutePosition\":\"\",\"size\":\"default\",\"fontSize\":\"\",\"column\":\"\"}"
};