window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0039/01_Awards Medley_GSM 2_160x600",
  "Creative": "HOP0039/01_Awards Medley_GSM 2",
  "Creative_Dimension": "160x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:.5,F2:.5,F3:2,F4:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "Awards and ratings are only one factor to consider when choosing a super fund. Visit hostplus.com.au/awards to learn more about our awards. Issued by Host-Plus Pty Limited. General advice only. Consider the relevant PDS and TMD available at hostplus.com.au before making a decision.",
  "CustomCSS": "",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideLineByLine:0.5,",
  "F1_LayoutClass": ",center",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":\"moveInRight:0.5:100:power1.out:0.5\",\"animationOut\":\"fadeOutLeft:0.25:100:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F1_Image2_a53029af.svg\",\"size\":\"70 77\",\"position\":\"46 120\",\"animationIn\":\"scaleUp:0.2:0.4:power1.out:0.5\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":true}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F1_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F1_Headline": "{\"text\":\"GAME.\",\"size\":\"36\",\"weight\":null,\"padding\":\"125 0 0 0\",\"order\":null,\"column\":null,\"delay\":\"0.5\",\"out\":null}",
  "F1_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F1_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideLineByLine:0.5,",
  "F2_LayoutClass": ",center",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":\"moveInRight:0.5:100:power1.out:0.5\",\"animationOut\":\"fadeOutLeft:0.25:100:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F2_Image2_a53029af.svg\",\"size\":\"68 75\",\"position\":\"48 260\",\"animationIn\":\"scaleUp:0.2:0.4:power1.out:0\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":true}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F2_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F2_Headline": "{\"text\":\"SET.\",\"size\":\"36\",\"weight\":null,\"padding\":\"265 0 0 0\",\"order\":null,\"column\":null,\"delay\":\"0\",\"out\":null}",
  "F2_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F2_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F2_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F3_Transitions": "cutIn",
  "F3_Animations": "slideLineByLine:0.2,",
  "F3_LayoutClass": ",center",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":\"moveInRight:0.5:100:power1.out:0.5\",\"animationOut\":\"fadeOutRight:0.25:100:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F3_Image2_a53029af.svg\",\"size\":\"68 75\",\"position\":\"47 400\",\"animationIn\":\"scaleUp:0.2:0.4:power1.out:0\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":true}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F3_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F3_Headline": "{\"text\":\"[MATCH.]\",\"size\":\"36\",\"weight\":null,\"padding\":\"405 0 0 0\",\"order\":null,\"column\":null,\"delay\":\"0.5\",\"out\":null}",
  "F3_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F3_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F4_Transitions": "",
  "F4_Animations": "slideLineByLine:0.5,",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F4_Image1_a53029af.svg\",\"size\":\"66\",\"position\":\"10 222\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:1.5\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":false}",
  "F4_Image2": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F4_Image2_a53029af.svg\",\"size\":\"62\",\"position\":\"11 295\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:2\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":false}",
  "F4_Image3": "{\"url\":\"assets/HOP0039_01_Awards_Medley_GSM_2_F4_Image3_a53029af.svg\",\"size\":\"62\",\"position\":\"11 362\",\"animationIn\":\"fadeInLeft:0.5:0:power1.out:2.5\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F4_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_footer.svg\",\"position\":null,\"maxSize\":\"140\",\"alignment\":null,\"delay\":\"2\"}",
  "F4_Headline": "{\"text\":\"Hostplus\\n[best Super \\nFund Winner]\",\"size\":\"21\",\"weight\":null,\"padding\":\"70 0\",\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F4_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F4_Cta": "{\"text\":\"Compare Hostplus\",\"alignment\":\"center\",\"position\":null,\"size\":null,\"labelSize\":\"large\",\"delay\":\"3\",\"out\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":null,\"ospSize\":null}",
  "F5_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F5_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}"
};