window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "YOU0080_NRL_Flexible Cover_300x250",
  "Creative": "YOU0080_NRL_Flexible Cover",
  "Creative_Dimension": "300x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:0",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "BorderColor": "",
  "BorderRadius": "",
  "CustomCSS": ".termsLink {z-index: 0!important}\n.cta {z-index: 1!important; margin-top: 0px}\n\n.frameFooter .terms {\nposition: absolute!important;\ntop: 220px!important;\n}",
  "ExitLink": "",
  "Terms": "Product issued by Youi Pty Ltd. Consider our Car PDS when deciding if the product is right for you. PDS & TMD available at youi.com.au",
  "TermsLabel": "{{More information >}}",
  "TermsLabelPosition": "",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideUpByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F1_InframeImage": "{\"url\":\"assets/YOU0080_NRL_Flexible_Cover_F1_InframeImage_64c771d0.jpg\",\"size\":\"280\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"0 0 30px 0\"}",
  "F1_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"220 186\",\"padding\":\"\",\"maxSize\":\"60\"}",
  "F1_Headline": "{\"text\":\"For pick ups, drop offs\\nand muddy boots.\",\"size\":\"24\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"9\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F1_Cta": "{\"text\":\"Start a quote\",\"alignment\":\"\",\"style\":\"\",\"position\":\"packed\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideUpByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F2_InframeImage": "{\"url\":\"assets/YOU0080_NRL_Flexible_Cover_F2_InframeImage_64c771d0.jpg\",\"size\":\"280\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"0 0 30px 0\"}",
  "F2_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"220 186\",\"padding\":\"\",\"maxSize\":\"60\"}",
  "F2_Headline": "{\"text\":\"Shop Youi’s flexible\\nComprehensive \\nCar Insurance.\",\"size\":\"24\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"9\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"100px 0 0 0\",\"delay\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": "fadeIn:0.5,",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F3_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"220 192\",\"padding\":\"\",\"maxSize\":\"60\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"|Youi Roadside Assist available<br>with Comprehensive policies only.<br>Exclusions, limits and additional fees may apply.<br>Cover not available within first 24 hours of<br>taking out, or upgrading to, Comprehensive cover.|\",\"size\":\"9\",\"weight\":400,\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"160px 0 0 0\",\"delay\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F4_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"border\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"delay\":\"\",\"animationIn\":\"\",\"animationOut\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\",\"order\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"border\":\"\"}",
  "F5_Logo": "{\"url\":\"YouiInlineLogo\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\",\"position\":\"\",\"padding\":\"\",\"delay\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"padding\":\"\",\"absolutePosition\":\"\",\"delay\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};