window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "Simon_AusPost_HalfPage_300x600",
  "Creative": "Simon_AusPost_HalfPage",
  "Creative_Dimension": "300x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2.4,F2:2",
  "Themes": "highlights,red,red,red,red",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "Bank@Post is an agency service provided by Australia Post on behalf of over 80 financial institutions. Bank@Post is available at participating Post Offices. Services available are withdrawals, deposits, and balance enquiries. Limits apply. Consult your financial institution for terms and conditions of the Bank@Post service.",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":\"assets/Simon_AusPost_HalfPage_F1_Image1_0acbfdc6.jpg\",\"size\":\"300 600\",\"position\":null,\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":\"assets/Simon_AusPost_HalfPage_F1_Image2_0acbfdc6.svg\",\"size\":null,\"position\":\"20 538\",\"animationIn\":null,\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":\"assets/Simon_AusPost_HalfPage_F1_Image3_0acbfdc6.svg\",\"size\":null,\"position\":\"222 20\",\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5440511/logo_aus_post_red.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null,\"layout\":null}",
  "F1_Headline": "{\"text\":\"No fees?\\nYes, please.\",\"size\":\"26\",\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":\"0\"}",
  "F1_Subheadline": "{\"text\":\"Withdraw, deposit or \\ncheck your balance\",\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":\"packed\"}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"color\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":\"assets/Simon_AusPost_HalfPage_F2_Image1_0acbfdc6.jpg\",\"size\":\"300 600\",\"position\":null,\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":\"assets/Simon_AusPost_HalfPage_F1_Image3_0acbfdc6.svg\",\"size\":null,\"position\":\"222 20\",\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5440511/logo_aus_post.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null,\"layout\":null}",
  "F2_Headline": "{\"text\":\"Here’s why\\nit’s easy to\\nBank@Post\",\"size\":null,\"weight\":null,\"padding\":\"0 0 20 0\",\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Subheadline": "{\"text\":\"> 80+ financial\\npartners onboard\\n>No fees from us\\n>Face-to-face\\nservice\",\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null}",
  "F2_Cta": "{\"text\":\"Find out more\",\"alignment\":null,\"position\":null,\"size\":null,\"color\":null}",
  "F3_Transitions": "",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null,\"layout\":null}",
  "F3_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"color\":null}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null,\"layout\":null}",
  "F4_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null}",
  "F4_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"color\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null,\"layout\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"color\":null}"
};