window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0307_AGL Car Giveaway_Display Movers_728x90",
  "Creative": "AGA0307_AGL Car Giveaway_Display Movers",
  "Creative_Dimension": "728x90",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:3,F2:2,F3:2,F4:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "Ends 10/6/2026. For customers 18+ who sign up to an eligible AGL service or whom AGL invites to enter. ++Prize per state++: BYD Atto 3, drive-away value from $47,224.10 (inc. GST). ++Draws++: 12pm 9/7/2026 at Level 9, 628 Bourke Street, Melbourne VIC 3000. Winners notified by phone/email and published at agl.com.au by 16/7/2026. ++T&Cs++ apply - see: agl.com.au/win. ++Permit Nos.++: NSW TP/04927. SA T26/239.",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": ",",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image1_ed35f974.png\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.5::power1.out\",\"animationOut\":\"moveOutLeft:0.5::power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image2": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image2_ed35f974.svg\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.5::power1.out\",\"animationOut\":\"moveOutLeft:0.5::power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image3_ed35f974.svg\",\"size\":\"728\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"moveInRight:.65::power1.out\",\"animationOut\":\"moveOutLeft:0.5::power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "cutIn",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",middle",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F2_Image1_ed35f974.svg\",\"size\":\"728\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.5::power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F2_Headline": "{\"text\":\"Move your [[energy]]\\n[[and internet with AGL.]]\",\"size\":\"23\",\"weight\":\"\",\"order\":\"2\",\"column\":\"ColumnA\"}",
  "F2_Subheadline": "{\"text\":\"                                                    \",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":null}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"25\",\"weight\":\"\",\"order\":\"1\",\"column\":\"ColumnA\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "colorWheel:1.7",
  "F3_Animations": "slideInByLine:0.5,",
  "F3_LayoutClass": ",middle",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F3_Image1_ed35f974.png\",\"size\":\"728\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"Every new service\\nis a chance to [WIN!]\",\"size\":\"23\",\"weight\":\"\",\"order\":\"\",\"column\":\"ColumnA\"}",
  "F3_Subheadline": "{\"text\":\"                                                    \",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":null}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image1_ed35f974.png\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image2_ed35f974.svg\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"assets/AGA0307_AGL_Car_Giveaway_Display_Movers_F1_Image3_ed35f974.svg\",\"size\":\"728\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F4_Cta": "{\"text\":\"LEARN MORE\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};