window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "APO0244_Travel_Campaign_2026_TravelInsurance_728x90",
  "Creative": "APO0244_Travel_Campaign_2026_TravelInsurance",
  "Creative_Dimension": "728x90",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:4,F3:2",
  "Themes": "red,red,red,red,red",
  "Overlay": "",
  "ExitLink": "https://auspost.com.au/travel-insurance",
  "Terms": "",
  "CustomCSS": ".inlineTerms {font-size: 9px; font-family: AP Type Pro Display Medium}\n.cta:hover {background: #FFFFFF!important; color:#dc1928; border:none }",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"assets/APO0244_Travel_Campaign_2026_TravelInsurance_F1_Image1_a8f15382.svg\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image2": "{\"url\":\"assets/APO0244_Travel_Campaign_2026_TravelInsurance_F1_Image2_a8f15382.svg\",\"size\":\"728 90\",\"position\":\"\",\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5440511/logo_aus_post.svg\",\"alignment\":\"logo-bottom-right\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\",\"layout\":\"\"}",
  "F1_Headline": "{\"text\":\"Save 10% on Travel Insurance \\nand go in the draw to win |$20K|\",\"size\":\"1.25rem\",\"weight\":700,\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F1_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_Terms": "{\"text\":\"T&Cs apply. 10% off Travel Insurance offer ends on 31 July 2026 and Prize draw offer ends on 31 May 2026.\\nThis draw is authorised under NSW Permit TP/04994,&nbsp&nbsp;ACT Permit TP <span>26</span><span>&#47;</span><span>00690</span> and SA Permit TP26/533.\",\"alignment\":\"left\",\"style\":\"\",\"position\":null}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"color\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"assets/APO0244_Travel_Campaign_2026_TravelInsurance_F2_Image2_a8f15382.svg\",\"size\":\"\",\"position\":\"0 -4\",\"animationIn\":\"moveInBottom:0.5:25:power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5440511/logo_aus_post.svg\",\"alignment\":\"logo-bottom-right\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\",\"layout\":\"\"}",
  "F2_Headline": "{\"text\":\"Plus other prizes\",\"size\":\"1.25rem\",\"weight\":700,\"padding\":\"0 0\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F2_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Terms": "{\"text\":\"T&Cs apply. 10% off Travel Insurance offer ends on 31 July 2026 and Prize draw offer ends on 31 May 2026.\\nThis draw is authorised under NSW Permit TP/04994,&nbsp&nbsp;ACT Permit TP <span>26</span><span>&#47;</span><span>00690</span> and SA Permit TP26/533.\",\"alignment\":\"left\",\"style\":\"\",\"position\":null}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"color\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": "slideInByLine:0.5,",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"assets/APO0244_Travel_Campaign_2026_TravelInsurance_F3_Image2_a8f15382.svg\",\"size\":\"728 90\",\"position\":\"\",\"animationIn\":\"fadeIn:0.5:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"0\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"1\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5440511/logo_aus_post.svg\",\"alignment\":\"logo-bottom-right\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\",\"layout\":\"\"}",
  "F3_Headline": "{\"text\":\"Award-winning Travel Insurance\",\"size\":\"1.25rem\",\"weight\":700,\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_Subheadline": "{\"text\":\"The travel mate you can rely on\",\"size\":\"0.9375rem\",\"weight\":500,\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F3_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_Terms": "{\"text\":\"T&Cs apply. 10% off Travel Insurance offer ends on 31 July 2026 and Prize draw offer ends on 31 May 2026.\\nThis draw is authorised under NSW Permit TP/04994,&nbsp&nbsp;ACT Permit TP <span>26</span><span>&#47;</span><span>00690</span> and SA Permit TP26/533.\",\"alignment\":\"left\",\"style\":\"\",\"position\":null}",
  "F3_Cta": "{\"text\":\"Find out more\",\"alignment\":\"\",\"position\":null,\"size\":\"0.79713rem\",\"color\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\",\"layout\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F4_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"color\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\",\"layout\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F5_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"color\":\"\"}"
};