window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0372_Smart Choice Update_Switch NSW-SA_300x600",
  "Creative": "AGA0372_Smart Choice Update_Switch NSW-SA",
  "Creative_Dimension": "300x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.025,F2:1,F3:3,F4:3",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "*You must stay with AGL at the\nsame address for 90 days from the commencement of the electricity/gas plan to receive this credit. Sign up online for one-off bill credits on selected AGL Electricity and Gas plans for new and moving residential customers only in NSW and SA where\nAGL operates. Credits are GST inclusive,\nnon-transferable, non-refundable. Full \nT&Cs at agl.com.au",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByBlock:0.5,",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":true}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F1_Headline": "{\"text\":\"\\n[[The]]\\n[[smart choice]]\",\"size\":\"40\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Subheadline": "{\"text\":\"Switch and stay\",\"size\":\"30\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": ",",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F2_Image1_7d50f3f8.svg\",\"size\":\"\",\"position\":\"0 0 \",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.75:200:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F2_Headline": "{\"text\":\"\",\"size\":\"47\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"30\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F3_Transitions": "colorWheel:1.7",
  "F3_Animations": ",",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F3_Image1_7d50f3f8.svg\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"moveInRight:0.75:200:power1.out\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F3_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F3_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F2_Image1_7d50f3f8.svg\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F3_Image1_7d50f3f8.svg\",\"size\":\"\",\"position\":\"0 0\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"assets/AGA0372_Smart_Choice_Update_Switch_NSW-SA_F4_Image3_7d50f3f8.svg\",\"size\":\"\",\"position\":\"210 20\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F4_Headline": "{\"text\":\"\\n[[The]]\\n[[smart choice]]\",\"size\":\"40\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Subheadline": "{\"text\":\"Switch and stay\",\"size\":\"30\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F4_Cta": "{\"text\":\"SWITCH NOW\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"svgType\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"maxSize\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Price": "{\"text\":\"\",\"size\":\"\",\"order\":\"\",\"column\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"column\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"absolutePosition\":\"\",\"size\":\"\",\"fontSize\":\"\",\"column\":\"\"}"
};