window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "AGA0312_SME ATL Credit Offer_Display_300x600",
  "Creative": "AGA0312_SME ATL Credit Offer_Display",
  "Creative_Dimension": "300x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:0.05,F2:2,F3:4,F4:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "++*You must stay with AGL at the same address for 90 days from the commencement of the electricity/gas plan to receive each credit.++ |$300 one-off credit on selected AGL electricity plans and $200 one-off credit on selected gas plans for new and moving Small Business customers only in NSW & VIC where AGL operates. Credit amounts are GST inclusive, non-transferable, non-refundable. Not available in conjunction with any other offer. Full T&Cs at agl.com.au|\n",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideInByLine:0.5,",
  "F1_LayoutClass": ",top",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F1_Image1_35935010.jpg\",\"size\":\"300\",\"position\":\"0 0\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":\"0 221\",\"svgType\":null,\"animationIn\":\"moveInRight:.4::power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F1_InframeImage_35935010.svg\",\"size\":null,\"position\":\"218 0 0 0\",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F1_Headline": "{\"text\":null,\"size\":\"22\",\"weight\":600,\"order\":null,\"column\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":\"33\",\"weight\":600,\"order\":null,\"column\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F1_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F1_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F1_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":\"packed\",\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideInByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",top",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F2_InframeImage_35935010.png\",\"size\":null,\"position\":\"224 0 0 0\",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F2_Headline": "{\"text\":\"Switch\\nand stay\\n[[with AGL]]\",\"size\":\"44\",\"weight\":600,\"order\":\"1\",\"column\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F2_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F2_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F2_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F3_Transitions": "colorWheel:1.7",
  "F3_Animations": "slideInByLine:0.5,",
  "F3_LayoutClass": ",top",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F3_Image1_35935010.svg\",\"size\":null,\"position\":\"25 275\",\"svgType\":null,\"animationIn\":\"moveInRight:1.5:700:power1.out\",\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F2_InframeImage_35935010.png\",\"size\":null,\"position\":\"224 0 0 0\",\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F3_Headline": "{\"text\":\"For up to \",\"size\":\"24\",\"weight\":600,\"order\":null,\"column\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F3_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F3_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F3_Cta": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":null,\"fontSize\":null,\"column\":null}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",top",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F4_Image1_35935010.svg\",\"size\":null,\"position\":\"25 250\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F1_Image1_35935010.jpg\",\"size\":\"300\",\"position\":\"0 0\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":\"assets/AGA0312_SME_ATL_Credit_Offer_Display_F1_InframeImage_35935010.svg\",\"size\":null,\"position\":\"0 218\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":\"0 0 \",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F4_Headline": "{\"text\":null,\"size\":\"24\",\"weight\":400,\"order\":\"1\",\"column\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F4_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F4_Terms": "{\"text\":\"{{*Click for T&Cs}}\",\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F4_Cta": "{\"text\":\"LEARN MORE\",\"alignment\":null,\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":\"default\",\"fontSize\":null,\"column\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",top",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":\"25 250\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":\"0 218 0 0\",\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"svgType\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":\"0 0 \",\"order\":\"1\",\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":\"logo-wedge-detached\",\"alignment\":null,\"position\":null,\"padding\":null,\"maxSize\":null}",
  "F5_Headline": "{\"text\":null,\"size\":\"28\",\"weight\":600,\"order\":\"2\",\"column\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null}",
  "F5_Price": "{\"text\":null,\"size\":null,\"order\":null,\"column\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"column\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":\"flex-start\",\"style\":null,\"position\":null,\"absolutePosition\":null,\"size\":\"default\",\"fontSize\":null,\"column\":null}"
};