window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0052_Indexed balanced FY26_Awards_300x600",
  "Creative": "HOP0052_Indexed balanced FY26_Awards",
  "Creative_Dimension": "300x600",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:1.5,F2:4,F3:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "The Hostplus Indexed Balanced option has one of the lowest fees of public offer funds’ balanced investment options (with 60-76% growth assets) as at 31/12/2025. Fee comparison conducted using SuperRatings SMART 2.0 system on 23/01/2026, based on a super account balance of $50,000. Refer to the PDS for more information. Awards and ratings are only one factor to consider when choosing a super fund. Visit hostplus.com.au/awards to learn more about our awards. General advice only. Consider the PDS and TMD at hostplus.com.au before deciding. Issued by Host-Plus Pty Limited.",
  "CustomCSS": "",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideLineByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F1_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F1_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_inline_300x600_100x41.svg\",\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F1_Headline": "{\"text\":\"[Hostplus \\nIndexed \\nbalanced\\noption]\",\"size\":\"32\",\"weight\":null,\"padding\":\"75 0 0 0\",\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F1_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F1_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F1_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F1_Terms": "{\"text\":\"{{Click for information}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F1_Cta": "{\"text\":\"Learn more\",\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F2_Transitions": "",
  "F2_Animations": "slideLineByLine:0.5,fadeOut:0.5",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F2_Image1": "{\"url\":\"assets/HOP0052_Indexed_balanced_FY26_Awards_F2_Image1_32119032.svg\",\"size\":\"75\",\"position\":\"15 320 0 0\",\"animationIn\":\"scaleUp:0.5:0.2:power1.out:1\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image2": "{\"url\":\"assets/HOP0052_Indexed_balanced_FY26_Awards_F2_Image2_32119032.svg\",\"size\":\"85\",\"position\":\"100 320 0 0\",\"animationIn\":\"scaleUp:0.5:0.2:power1.out:1.5\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Image3": "{\"url\":\"assets/HOP0052_Indexed_balanced_FY26_Awards_F2_Image3_32119032.svg\",\"size\":\"85\",\"position\":\"200 320 0 0\",\"animationIn\":\"scaleUp:0.5:0.2:power1.out:2\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":null,\"animatedSVG\":null}",
  "F2_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F2_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_inline_300x600_100x41.svg\",\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F2_Headline": "{\"text\":\"An award-\\nwinning \\n[low-cost \\nsuper product]\",\"size\":\"32\",\"weight\":null,\"padding\":\"75 0 0 0\",\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F2_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F2_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F2_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F2_Terms": "{\"text\":\"{{Click for information}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F2_Cta": "{\"text\":\"Learn more\",\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F3_Transitions": "",
  "F3_Animations": "slideLineByLine:0.5,fadeOut:1",
  "F3_LayoutClass": ",",
  "F3_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F3_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F3_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F3_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_inline_300x600_100x41.svg\",\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F3_Headline": "{\"text\":\"[Hostplus\\nIndexed\\nbalanced \\noption]\",\"size\":\"34\",\"weight\":null,\"padding\":\"75 0 0 0\",\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F3_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F3_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F3_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F3_Terms": "{\"text\":\"{{Click for information}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F3_Cta": "{\"text\":\"Learn more\",\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F4_Transitions": "",
  "F4_Animations": "slideLineByLine:0.5,",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F4_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F4_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":false,\"ospSize\":null}",
  "F4_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_packed.svg\",\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F4_Headline": "{\"text\":\"Frame\\n[four]\",\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F4_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F4_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F4_Terms": "{\"text\":\"{{Click for terms}}\",\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F4_Cta": "{\"text\":\"CTA\",\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null}",
  "F5_Image1": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image2": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Image3": "{\"url\":null,\"size\":null,\"position\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_InframeImage": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_ProductIcon": "{\"url\":null,\"size\":null,\"position\":null,\"order\":null,\"alignment\":null,\"alignmentPortrait\":null,\"column\":null,\"animationIn\":null,\"animationOut\":null,\"frameOut\":null,\"animatedSVG\":null}",
  "F5_Logo": "{\"url\":null,\"alignment\":null,\"position\":null,\"padding\":null,\"layout\":null,\"osp\":null,\"ospSize\":null}",
  "F5_Tap": "{\"url\":null,\"position\":null,\"maxSize\":null,\"alignment\":null,\"delay\":null}",
  "F5_Headline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_Headline2": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Subheadline": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"out\":null}",
  "F5_icontext": "{\"text\":null,\"size\":null,\"weight\":null,\"padding\":null,\"order\":null,\"column\":null,\"delay\":null,\"direction\":null,\"out\":null}",
  "F5_price": "{\"text\":null,\"padding\":null,\"position\":null,\"preText\":null,\"product\":null,\"disclaimer\":null,\"roundel\":null,\"size\":null,\"weight\":null,\"order\":null,\"column\":null,\"delay\":null}",
  "F5_Terms": "{\"text\":null,\"alignment\":null,\"style\":null,\"position\":null,\"out\":null}",
  "F5_Cta": "{\"text\":null,\"alignment\":null,\"position\":null,\"size\":null,\"labelSize\":null,\"delay\":null,\"out\":null}"
};