window.MANIFEST = {
  "Unique_ID": "",
  "Reporting_Label": "HOP0036_CPIplus Display_Update_300x250",
  "Creative": "HOP0036_CPIplus Display_Update",
  "Creative_Dimension": "300x250",
  "Targeting_ID": "",
  "Placement_ID": "",
  "Rotation": "",
  "Start_Date": "",
  "End_Date": "",
  "Default": "",
  "Active": "",
  "FrameOrder": "F1:2,F2:7,F3:2",
  "Themes": "default,default,default,default,default",
  "Overlay": "",
  "ExitLink": "",
  "Terms": "",
  "CustomCSS": ".F3 .highlight {text-transform: none !important; line-height:28px !important;}",
  "Layouts": ",,,,",
  "F1_Transitions": "",
  "F1_Animations": "slideLineByLine:0.5,fadeOut:0.5",
  "F1_LayoutClass": ",",
  "F1_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F1_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F1_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F1_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F1_Headline": "{\"text\":\"[how much]\\n[certainty]\\ndo you want in\\nretirement?\",\"size\":\"26\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F1_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F1_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F1_Terms": "{\"text\":\"General advice only. Consider the Hostplus Pension PDS and TMD  at hostplus.com.au before deciding. Returns above inflation are set annually, but Hostplus may shorten the return period. Hostplus  may adjust the rate of return with at least 30 days’ notice. Past performance is not a reliable indicator of future returns. Issued by Host-Plus Pty Limited ABN 79 008 634 704.\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F1_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Transitions": "",
  "F2_Animations": ",",
  "F2_LayoutClass": ",",
  "F2_Video": "{\"url\":\"assets/HOP0036_CPIplus_Display_Update_F2_Video_62313855.mp4\",\"size\":\"260\",\"position\":\"\",\"animationIn\":\"fadeIn:0.25:power1.out\",\"animationOut\":\"fadeOut:0.5:power1.in\",\"frameOut\":\"\"}",
  "F2_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F2_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F2_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F2_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F2_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F2_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F2_Terms": "{\"text\":\"General advice only. Consider the Hostplus Pension PDS and TMD  at hostplus.com.au before deciding. Returns above inflation are set annually, but Hostplus may shorten the return period. Hostplus  may adjust the rate of return with at least 30 days’ notice. Past performance is not a reliable indicator of future returns. Issued by Host-Plus Pty Limited ABN 79 008 634 704.\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F2_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_Transitions": "",
  "F3_Animations": "slideLineByLine:0.5,",
  "F3_LayoutClass": ",middle",
  "F3_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F3_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F3_Logo": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/logo_hostplus_isf.svg\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F3_Tap": "{\"url\":\"https://s0.2mdn.net/creatives/assets/5512546/tap_hoz_inline_300x250.svg\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\".25\"}",
  "F3_Headline": "{\"text\":\"<span style=\\\"\\\">[CPIplus]</span>\\naveraged 6.94% \\np.a. for retirees\",\"size\":\"24\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Subheadline": "{\"text\":\"From 1 July 2021 to 30 June 2025\",\"size\":\"14\",\"weight\":\"Effra Regular\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F3_icontext": "{\"text\":\" \",\"size\":\"14\",\"weight\":\"\",\"padding\":\"\",\"order\":\"3\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F3_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F3_Terms": "{\"text\":\"General advice only. Consider the Hostplus Pension PDS and TMD  at hostplus.com.au before deciding. Returns above inflation are set annually, but Hostplus may shorten the return period. Hostplus  may adjust the rate of return with at least 30 days’ notice. Past performance is not a reliable indicator of future returns. Issued by Host-Plus Pty Limited ABN 79 008 634 704.\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F3_Cta": "{\"text\":\"Switch now\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"1.25\",\"out\":\"\"}",
  "F4_Transitions": "",
  "F4_Animations": ",",
  "F4_LayoutClass": ",",
  "F4_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F4_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F4_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F4_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F4_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F4_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F4_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F4_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F4_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Transitions": "",
  "F5_Animations": ",",
  "F5_LayoutClass": ",",
  "F5_Video": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\"}",
  "F5_Image1": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image2": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Image3": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_InframeImage": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_ProductIcon": "{\"url\":\"\",\"size\":\"\",\"position\":\"\",\"order\":\"\",\"alignment\":\"\",\"alignmentPortrait\":\"\",\"column\":\"\",\"animationIn\":\"\",\"animationOut\":\"\",\"frameOut\":\"\",\"animatedSVG\":\"\"}",
  "F5_Logo": "{\"url\":\"\",\"alignment\":\"\",\"position\":\"\",\"padding\":\"\",\"layout\":\"\",\"osp\":\"\",\"ospSize\":\"\"}",
  "F5_Tap": "{\"url\":\"\",\"position\":\"\",\"maxSize\":\"\",\"alignment\":\"\",\"delay\":\"\"}",
  "F5_Headline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_Headline2": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Subheadline": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"out\":\"\"}",
  "F5_icontext": "{\"text\":\"\",\"size\":\"\",\"weight\":\"\",\"padding\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\",\"direction\":\"\",\"out\":\"\"}",
  "F5_price": "{\"text\":\"\",\"padding\":\"\",\"position\":\"\",\"preText\":\"\",\"product\":\"\",\"disclaimer\":\"\",\"roundel\":\"\",\"size\":\"\",\"weight\":\"\",\"order\":\"\",\"column\":\"\",\"delay\":\"\"}",
  "F5_Terms": "{\"text\":\"\",\"alignment\":\"\",\"style\":\"\",\"position\":\"\",\"out\":\"\",\"padding\":\"\"}",
  "F5_Cta": "{\"text\":\"\",\"alignment\":\"\",\"position\":\"\",\"size\":\"\",\"labelSize\":\"\",\"delay\":\"\",\"out\":\"\"}"
};